# Generated by Django 5.1.6 on 2025-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('D', 'decline')], default='P', max_length=3),
            preserve_default=False,
        ),
    ]
