# Generated by Django 5.1.6 on 2025-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('D', 'decline')], max_length=10),
        ),
    ]
