# Generated by Django 5.1.6 on 2025-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('D', 'decline')], default='P', max_length=10),
        ),
    ]
